name: Build AllRecipes Scraper EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install pkg
        run: npm install -g pkg

      - name: Build EXE
        run: pkg . --targets node18-win-x64 --output allrecipes-scraper.exe

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v3
        with:
          name: allrecipes-scraper-exe
          path: allrecipes-scraper.exe
